version: '3'
services:
  top.api:
    image: ghcr.io/xartv/mytop-api:main
    container_name: top-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017
    volumes:
      - ./db/mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5
